### ISSUE TITLE
[ BUG ] Local anime is having problems while checking library 

### ISSUE THREAD

**Issue by soymadip** [aniyomiorg/aniyomi#1060]
### Steps to reproduce

1. Add some local animes following the official guide. 
2. Add them to library. 
3. Now after some time, in one of the local anime, add more episodes.
4. Now it will give the error message
5. Also daily update gives the error message too.

### Expected behavior

No error comes and library is successfully updated.

### Actual behavior

Message is giving me this error:-

```python
! Serializer for class 'AnimeDetails' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
  # Local anime source
    - Detective Conan
    - Fate
    - Movie
    - One piece
```

### Crash logs

```python
--------- beginning of crash
07-09 00:23:11.968 24659 24659 E AndroidRuntime: FATAL EXCEPTION: main
07-09 00:23:11.968 24659 24659 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 24659
07-09 00:23:11.968 24659 24659 E AndroidRuntime: java.lang.NullPointerException
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at is.xyz.mpv.MPVView.loadChapters(MPVView.kt:12)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.updateChapters(PlayerActivity.kt:232)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.eventPropertyUi$app_standardPreview(PlayerActivity.kt:23)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerObserver.$r8$lambda$XH0MxcEvV4snA4Hszw3UBnmRa_M(PlayerObserver.kt:13)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerObserver$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:5)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8381)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
07-09 00:23:11.968 24659 24659 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
--------- beginning of main
07-10 17:54:32.007 17570 17570 E hiyomi.mi.debug: Unknown bits set in runtime_flags: 0x40000000
07-10 17:54:32.178 17570 17570 E hiyomi.mi.debug: sysOpen failed with error=Permission denied
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: Settings request failed.
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/:::443
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:93)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:71)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:13)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.1:13)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:3)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:6)
07-10 17:54:32.691 17570 17598 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:1012)
07-10 17:54:32.830 17570 17720 E SQLiteLog: (284) automatic index on C(anime_id)
07-10 17:54:32.830 17570 17720 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
07-10 17:54:32.915 17570 17570 E IPCThreadState: attemptIncStrongHandle(76): Not supported
App version: 0.14.5-6424 (standard, 51fff13b7, 99, 2023-06-21T21:45Z)
Android version: 13 (SDK 33)
Android build ID: RMX3461_11_F.08
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461
```

### Aniyomi version

[BETA] App version: 0.14.5-6424 (standard, 51fff13b7, 99, 2023-06-21T21:45Z) 

### Android version

Android 13

### Device

Android version: 13 (SDK 33) Android build ID: RMX3461_11_F.08 Device brand: realme Device manufacturer: realme Device name: RE54BFL1 Device model: RMX3461 Device product name: RMX3461

### Other details

The update error message gave this file:- 
[Aniyomi Bug.txt](https://github.com/aniyomiorg/aniyomi/files/12001799/Aniyomi.Bug.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Fixed in #1077
