### ISSUE TITLE
Update function not working

### ISSUE THREAD

**Issue by Chanki33** [aniyomiorg/aniyomi#1426]
### Steps to reproduce

1. Open the update tab
2. Click on update (or the refresh) button 

### Expected behavior

Every anime should be updated and show the new episodes that were released after the last refresh.

### Actual behavior

No anime is being updated. 

### Crash logs

App version: 0.15.2.4 (standard, 16361e5, 121, 2024-01-28T19:30Z)
Android version: 12 (SDK 32; build JIO.LS1542QWN.001.06.035.200123-193954)
Android build ID: JIO.LS1542QWN.001.06.035.200123-193954
Device brand: Jio
Device manufacturer: Jio
Device name: LS1542QWN (JioPhoneNext)
Device model: LS1542QWN
WebView: Android System WebView 121.0.6167.164

Problematic extensions:
- 999Hentai
  Installed: 1.4.5 / Available: ?
  Obsolete: true
- Bato.to
  Installed: 1.4.32 / Available: ?
  Obsolete: true
- MangaClash
  Installed: 1.4.35 / Available: ?
  Obsolete: true
- MangaForFree.net
  Installed: 1.4.33 / Available: ?
  Obsolete: true
- MangaReader
  Installed: 1.4.4 / Available: ?
  Obsolete: true
- Mangakakalot
  Installed: 1.4.8 / Available: ?
  Obsolete: true
- Manganato
  Installed: 1.4.7 / Available: ?
  Obsolete: true
- OnlyManhwa
  Installed: 1.4.32 / Available: ?
  Obsolete: true
- VIZ
  Installed: 1.4.20 / Available: ?
  Obsolete: true

--------- beginning of main
02-14 06:36:12.231  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:36:12.231  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:36:12.231  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:36:12.231  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:36:12.231  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:36:12.231  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:36:12.231  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:36:12.231  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:36:12.282  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:36:12.282  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:36:12.282  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:36:12.282  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:36:12.282  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:36:12.282  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:36:12.282  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:36:12.282  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:36:12.866  3535  2657 E DatabaseUtils: Writing exception to parcel
02-14 06:36:12.866  3535  2657 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:36:12.866  3535  2657 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:36:12.866  3535  2657 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:36:12.866  3535  2657 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:36:12.866  3535  2657 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:36:12.866  3535  2657 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:36:12.866  3535  2657 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:21.382  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:21.382  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:21.382  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:21.382  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:21.382  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:21.382  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:21.382  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:21.382  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:21.427  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:21.427  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:21.427  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:21.427  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:21.427  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:21.427  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:21.427  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:21.427  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:21.550  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:21.550  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:21.550  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:21.550  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:21.550  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:21.550  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:21.550  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:21.550  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:27.879  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:27.879  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:27.879  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:27.879  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:27.879  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:27.879  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:27.879  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:27.879  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:27.938  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:27.938  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:27.938  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:27.938  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:27.938  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:27.938  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:27.938  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:27.938  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:28.046  3535  2657 E DatabaseUtils: Writing exception to parcel
02-14 06:37:28.046  3535  2657 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:28.046  3535  2657 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:28.046  3535  2657 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:28.046  3535  2657 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:28.046  3535  2657 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:28.046  3535  2657 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:28.046  3535  2657 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:34.770  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:34.770  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:34.770  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:34.770  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:34.770  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:34.770  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:34.770  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:34.770  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:34.801  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:34.801  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:34.801  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:34.801  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:34.801  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:34.801  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:34.801  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:34.801  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
02-14 06:37:34.876  3535  2687 E DatabaseUtils: Writing exception to parcel
02-14 06:37:34.876  3535  2687 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=1613, uid=1000 requires the provider be exported, or grantUriPermission()
02-14 06:37:34.876  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
02-14 06:37:34.876  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
02-14 06:37:34.876  3535  2687 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
02-14 06:37:34.876  3535  2687 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 06:37:34.876  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-14 06:37:34.876  3535  2687 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)

### Aniyomi version

15.2.4

### Android version

Android 12

### Device

Jio Phone Next 

### Other details

Episodes are showing if I individually update each anime which is expected to be released, but it doesn't do the same in the update tab.

And I haven't changed my settings for a long while.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Chanki33** [comment]
Sorry, settings problem
