### ISSUE TITLE
Aniyomi keeps crashing without any reason ( cannot provide crash log ).

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#440]
### Steps to reproduce

1. Open aniyomi 
2. Aniyomi crashed 
3. "Aniyomi keeps stopping unexpectedly"
4. No crash logs can be seen in the cache directory because I cannot even open the app to dump the crash logs -____-

### Expected behavior

I expected the app to open. 

### Actual behavior

But it crashed without any reason.

### Crash logs

No crash logs can be seen in that directory 

### Aniyomi version

Aniyomi v0.12.3.6 ( Stable)

### Android version

Android 7.11

### Device

Motorola Moto E4 

### Other details

This issue is basically a duplicate of https://github.com/jmir1/aniyomi/issues/359 and people are still having this issue but there is no response on that issue. 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by jmir1** [comment]
try using this app to read the crash log:
https://play.google.com/store/apps/details?id=com.dp.logcatapp

**Comment by jmir1** [comment]
um not sure
i dont remember

**Comment by prorounak2005** [comment]
> um not sure i dont remember

time: 1647549380257
msg: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.jmir.tachiyomi.mi/eu.kanade.tachiyomi.ui.main.MainActivity}: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3636)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3793)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7837)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
at android.webkit.CookieManager.getInstance(CookieManager.java:50)
at eu.kanade.tachiyomi.network.AndroidCookieJar.(AndroidCookieJar.kt:2)
at eu.kanade.tachiyomi.network.NetworkHelper.(NetworkHelper.kt:6)
at eu.kanade.tachiyomi.AppModule$registerInjectables$6.invoke(AppModule.kt:1)
at eu.kanade.tachiyomi.AppModule$registerInjectables$6.invoke(AppModule.kt:2)
at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:1)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:4)
at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:4)
at uy.kohesive.injekt.api.InjektScope.getInstance(Unknown Source:7)
at eu.kanade.tachiyomi.data.track.TrackService$special$$inlined$injectLazy$2.invoke(Injekt.kt:3)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
at eu.kanade.tachiyomi.data.track.TrackService.getNetworkService(TrackService.kt:1)
at eu.kanade.tachiyomi.data.track.komga.Komga.(Komga.kt:2)
at eu.kanade.tachiyomi.data.track.TrackManager.(TrackManager.kt:7)
at eu.kanade.tachiyomi.AppModule$registerInjectables$16.invoke(AppModule.kt:1)
at eu.kanade.tachiyomi.AppModule$registerInjectables$16.invoke(AppModule.kt:2)
at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:1)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:4)
at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:4)
at uy.kohesive.injekt.api.InjektScope.getInstance(Unknown Source:7)
at eu.kanade.tachiyomi.ui.animelib.AnimelibSettingsSheet.(AnimelibSettingsSheet.kt:3)
at eu.kanade.tachiyomi.ui.animelib.AnimelibController.onViewCreated(AnimelibController.kt:17)
at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(BaseController.kt:1)
at com.bluelinelabs.conductor.Controller.inflate(Controller.java:12)
at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:17)
at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
at com.bluelinelabs.conductor.Router.setBackstack(Router.java:71)
at com.bluelinelabs.conductor.Router.setRoot(Router.java:3)
at eu.kanade.tachiyomi.ui.base.controller.ConductorExtensionsKt.setRoot(ConductorExtensions.kt:1)
at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(NavigationBarView.java:19)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:5)
at com.google.android.material.navigation.NavigationBarView.setSelectedItemId(NavigationBarView.java:2)
at eu.kanade.tachiyomi.ui.main.MainActivity.setSelectedNavItem(MainActivity.kt:2)
at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:61)
at android.app.Activity.performCreate(Activity.java:8051)
at android.app.Activity.performCreate(Activity.java:8031)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1342)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3609)
... 12 more
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
... 53 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:428)
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)

These are the crash logs

**Comment by jmir1** [comment]
Thanks that's really helpful I'll see if I can fit that issue 🙏

**Comment by prorounak2005** [comment]
Actually  these problems are happening in older android phones ( android 6 -  7) I already read the aniyomi wiki. Aniyomi wiki is awesome because everything us clearly written there and it says that we need the android system webview for android 6.0 -7.0 devices for aniyomi to work and I updated my android system webview but still it crashes whenever I open the app but when I uninstall and reinstall the app everything works fine ( well only for 2 to 3 days) and then it again crashes. :(
